### ISSUE TITLE
Add function to set the system time from this lib?

### ISSUE THREAD

**Issue by tripflex** [nliviu/ds3231#1]
Going off your post on the forums I was able to easily add my own function to call `mgos_settimeofday()`, found here:
https://forum.mongoose-os.com/discussion/2270/set-time-of-day-from-source-other-than-sntp-using-javascript

But maybe it would be good to add a helper function in this lib to set it with?

Either way, THANK YOU for posting this, the code looks beautiful, well documented and organized, worked immediately for me, i'll submit a PR here soon for the README to add some documentation to the lib to help others, but I think this should be the official ds3231 lib over the one available right now under mos libs github 👍

**Comment by nliviu** [comment]
The library was intended for my own use. I've seen you were interested in a DS3231 Mongoose OS implementation and published it.
As soon as I'll have some spare time to better document it, I'll publish the library in the mongoose-os-libs repo.

**Comment by nliviu** [comment]
cbce8477487152af09de8a66e8211aa44b4d270d
